// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaA1e_mqgw-pFUNhGfri3YmU48GABXF7w',
    appId: '1:699436605619:web:1cfa72688dbcfe186610c6',
    messagingSenderId: '699436605619',
    projectId: 'mltmenu',
    authDomain: 'mltmenu.firebaseapp.com',
    storageBucket: 'mltmenu.appspot.com',
    measurementId: 'G-FQZTDC0BDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT0ydFg1_DkEtsLS6saG5al7L59pALaGU',
    appId: '1:699436605619:android:e1ba5000ec39d8926610c6',
    messagingSenderId: '699436605619',
    projectId: 'mltmenu',
    storageBucket: 'mltmenu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARjUpadcj78ZBOSRQvzuVCfzKftmsKGWg',
    appId: '1:699436605619:ios:c6481feadeca927a6610c6',
    messagingSenderId: '699436605619',
    projectId: 'mltmenu',
    storageBucket: 'mltmenu.appspot.com',
    iosBundleId: 'com.example.adminMltMenuMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARjUpadcj78ZBOSRQvzuVCfzKftmsKGWg',
    appId: '1:699436605619:ios:5e98f0282686d2296610c6',
    messagingSenderId: '699436605619',
    projectId: 'mltmenu',
    storageBucket: 'mltmenu.appspot.com',
    iosBundleId: 'com.example.adminMltMenuMobile.RunnerTests',
  );
}
